* Modified version of the "Hack" typeface

This is the typeface I use in [[https://protesilaos.com/dotemacs][my Emacs setup]].  It contains a set of
glyphs that slightly differentiate it from the upstream distribution.
The source of the patched glyphs is the [[https://github.com/source-foundry/alt-hack][alt-hack repository]] provided by
the authors of Hack itself.

The [[https://gitlab.com/protesilaos/hack-font-mod/-/wikis/Pictures][pictures in the wiki]] summarise my changes.  Detailed descriptions
are offered below.  In parentheses I mention the glyph code from the
alt-hack repo, else I refer to the upstream version.

** Regular and bold

+ =0= with a forward slash (u0030-forwardslash).
+ =1= with no bottom slab (u0031-noslab).
+ =3= with a flat top (u0033-flattop).
+ =i= with a bottom slab to disambiguate it from =1=, =l= (u0069-slab).
+ =f= with no descender (upstream)

** Italic and bold italic

+ =0= with a forward slash (u0030-forwardslash).
+ =1= with bottom slab to disambiguate it from =i=, =l= (upstream).
+ =3= with a curved top (upstream)
+ =i= with no bottom slab (upstream).
+ =f= with a descender (u0066-knife).

** Rationale

+ The default =0= looks like a filled-in circle at small point sizes.  It
  also appears like a Greek theta =θ= when cast in bold weight.  Whereas
  the slashed zero is the best at all point sizes and styles.  Compared
  to other alternatives, a dotted zero can have problems with the
  horizontal alignment of the dot, meaning that only some font sizes are
  good enough.  Same for the diamond zero.
+ The slab-less =1= fits in better with other numerals, especially in
  tabular interfaces with lots of numbers.  Same for the =3= with a flat
  top.  Such interfaces are typically presented in roman letter forms
  (regular or bold).  In other contexts where italics can be used we
  allow these numbers to use more curved forms: the flat top of the =3=
  contradicts the overall impression of the slant, while the slabbed =1=
  distinguishes it from either =i= or =l=.
+ The slab in the =i= helps fill in the notional space between its lower
  part and whatever letter precedes it.  This avoids scenaria in body
  copy where letter combinations involving the =i= seem to be further
  apart than they actually are.  For italic styles, the bottom slab does
  not look right since it remains anchored to the baseline, so =i= is
  allowed to follow the aesthetics of =l= (and hence why the =1= is tweaked
  accordingly, with the assumption that an oblique =i= is more common than
  a corresponding =1=).
+ The slanted =f= with a descender makes it easier to follow the rhythm of
  common letter combinations (=fi=, =fl=), in accordance with the above
  considerations.

** Build information

I built this set of files on 2020-02-25 while running a Debian
Bullseye/Sid system.  It all started by cloning the [[https://github.com/source-foundry/Hack][main Hack repo]],
switching to the =dev= branch at commit =db2d3feb7= and then replacing the
selected glyphs with their alt-hack equivalents.

** Copying

Shared under the same free/libre permissive terms as Hack (see COPYING).
